tarefa/Models/Cadastro.cs
using System;

namespace tarefa.Models
{
    public class Cadastro
    {
        public Cadastro(){}

        public Cadastro(int id, float prioridade, string nameTarefa, string data, int percent)
        {
            this.id=id;
            this.prioridade = prioridade;
            this.nameTarefa = nameTarefa;
            this.data = data;
            this.percent = percent;
        }
        public int id {get; set;}
        public float prioridade { get; set; }
        public string nameTarefa { get; set; }

        public string data { get; set; }     
        public int percent {get; set;}   

    }    
}

tarefa/Models/CadastroRepository.cs
using System;
using System.Collections.Generic;
using System.Linq;

namespace tarefa.Models
{
    public class CadastroRepository
    {
         public static List<Cadastro> cad1 = new List<Cadastro>();
    
        public CadastroRepository()
        {           
        }

        public void Create(Cadastro cad)
        {
            cad1.Add(cad);
        }
        public List<Cadastro> GetAll()
        {
            return cad1;
        }

         public List<Cadastro> GetAbertas()
        {
            return cad1.Where(x=>x.percent < 100).ToList();
        }

         public List<Cadastro> GetPorcento()
        {
            return cad1.Where(x=>x.percent == 100).ToList();
        }
        
        public Cadastro GetById(int id)
        {
            return cad1.Find(x=>x.id == id);
        }
        
        public void Delete(int id)
        {
            cad1.Remove(GetById(id));

        }

        public void Dell(int percent){
            cad1.Remove(GetByPercent(percent));
        }

        private Cadastro GetByPercent(int percent)
        {
            throw new NotImplementedException();
        }

        public void Update(Cadastro cad)
        {
            var index = cad1.FindIndex(x=>x.id == cad.id);
            cad1[index].prioridade = cad.prioridade;
            cad1[index].nameTarefa = cad.nameTarefa;
            cad1[index].data = cad.data;
            cad1[index].percent = cad.percent;
        }

        
    }
    }

tarefa/Models/ErrorViewModel.cs
using System;

namespace tarefa.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

tarefa/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using tarefa.Models;

namespace tarefa.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

tarefa/Controllers/TarefaController.cs
using tarefa.Models;
using Microsoft.AspNetCore.Mvc;

namespace tarefa.Controllers
{
    public class TarefaController : Controller
    {
        CadastroRepository _repository = 
        new CadastroRepository();

        public IActionResult Index()
        {
            var cad1 = _repository.GetAll();          

            return View(cad1);
        }

        public IActionResult Abertas()
        {
            var cad1 = _repository.GetAbertas();          

            return View(cad1);
        }

        public IActionResult Concluidas()
        {
            var cad1 = _repository.GetPorcento();          

            return View(cad1);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Cadastro cad)
        {
            _repository.Create(cad);

            return RedirectToAction("index");
        }

        public IActionResult Delete(int id)
        {
            _repository.Delete(id);
            return RedirectToAction("Index");
        }

        public IActionResult Dell(int percent)
        {
            _repository.Dell(percent);
            return RedirectToAction("Index");
        }

       [HttpGet]
        public IActionResult Edit(int id)
        {
            var per = _repository.GetById(id);
            return View(per);
        }

        [HttpPost]
        public IActionResult Edit(Cadastro cadAlterado)
        {
            _repository.Update(cadAlterado);

            return RedirectToAction("index");
        }
    
    }
}

tarefa/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

tarefa/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - tarefa</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"/>
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">tarefa</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Tarefa" asp-action="Index">Tarefas</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Tarefa" asp-action="Abertas">Abertas</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Tarefa" asp-action="Concluidas">Concluidas</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - tarefa - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>

tarefa/Views/Tarefa/Abertas.cshtml
@model IEnumerable<tarefa.Models.Cadastro>
    
<div class="container">
    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Prioridade</th>
                <th>Nome Tarefa</th>
                <th>Data</th>
                <th>Percentual </th>
                <th></th>
                <th></th>
            </tr>
            </tr>
        </thead>

    @foreach(var item in Model)
        {
                <tr>
                    <td>@item.id</td>
                    <td>@item.prioridade</td>
                    <td>@item.nameTarefa</td>
                    <td>@item.data</td>
                    <td>@item.percent</td>
                </tr>            
        }
    </table>
</div>

tarefa/Views/Tarefa/Concluidas.cshtml
@model IEnumerable<tarefa.Models.Cadastro>
    
<div class="container">
    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Prioridade</th>
                <th>Nome Tarefa</th>
                <th>Data</th>
                <th>Percentual </th>
                <th></th>
                <th></th>
            </tr>
            </tr>
        </thead>
        @foreach(var item in Model)
        {
            <tr>
                <td>@item.id</td>
                <td>@item.prioridade</td>
                <td>@item.nameTarefa</td>
                <td>@item.data</td>
                <td>@item.percent</td>
               <td><a class="btn btn-danger" href="Tarefa/Dell/@item.id">Delete</a> </td>
            </tr>
        }
     </table>
</div>

        

tarefa/Views/Tarefa/Create.cshtml
<div class="form-horizontal">
    <form action="Create" method="Post">

        <div class="form-group">
            <label>Id</label>
            <input  class="form-control"
                    type="text" name="id"/>
        </div>

        <div class="form-group">
            <label>Prioridade</label>
            <input  class="form-control"
                    type="text" name="prioridade"/>
        </div>

        <div class="form-group">
            <label>Nome Tarefa</label>
            <input  class="form-control"
                    type="text" name="nameTarefa"/>
        </div>

        <div class="form-group">
            <label>Data</label>
            <input  class="form-control"
                    type="text" name="data"/>
        </div>

        <div class="form-group">
            <label>Percentual</label>
            <input  class="form-control"
                    type="text" name="percent"/>
        </div>

        <input  class="btn btn-primary" 
                type="submit" value="Salvar"/>

    </form>
</div>

tarefa/Views/Tarefa/Edit.cshtml
@model tarefa.Models.Cadastro

<div class="form-horizontal">
    <form action="Edit" method="Post">

        <div class="form-group">
            <label>Id</label>
            <input  class="form-control"
                    type="text" name="id"
                    value="@Model.id"/>
        </div>

        <div class="form-group">
            <label>Prioridade</label>
            <input  class="form-control"
                    type="text" name="prioridade"
                    value="@Model.prioridade"/>
        </div>

        <div class="form-group">
            <label>Nome Tarefa</label>
            <input  class="form-control"
                    type="text" name="nameTarefa"
                    value="@Model.nameTarefa"/>
        </div>

        <div class="form-group">
            <label>Data</label>
            <input  class="form-control"
                    type="text" name="data"
                    value="@Model.data"/>
        </div>

        <div class="form-group">
            <label>Percentual</label>
            <input  class="form-control"
                    type="text" name="percent"
                    value="@Model.percent"/>
        </div>

        <input  class="btn btn-primary" 
                type="submit" value="Salvar"/>

    </form>
</div>

tarefa/Views/Tarefa/Index.cshtml
@model IEnumerable<tarefa.Models.Cadastro>
</br></br>
<a href="Tarefa/Create" class="btn btn-primary">Nova Tarefa</a>
</br></br>

<div class="container">
    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Prioridade</th>
                <th>Nome Tarefa</th>
                <th>Data</th>
                <th>Percentual </th>
                <th></th>
                <th></th>
            </tr>
            </tr>
        </thead>

        @foreach(var item in Model)
        {
            <tr>
                <td>@item.id</td>
                <td>@item.prioridade</td>
                <td>@item.nameTarefa</td>
                <td>@item.data</td>
                <td>@item.percent</td>
                <td><a class="btn btn-danger" href="Tarefa/Delete/@item.id">Delete</a> </td>
                <td><a class="btn btn-primary" href="Tarefa/Edit/@item.id">Editar</a> </td>
            </tr>
        }
    </table>
</div>